Add wait for it script to ensure db ready before starting backend
hovedstyret/indok-web pull request #316
Opened 2021-11-01 19:40 UTC by Jorgro

## Proposed Changes
- Add [wait-for-it.sh](https://github.com/vishnubob/wait-for-it) to `entrypoint.sh` to ensure that the DB is available before the Backend tries to connect. While there is a `depends_on` in the Docker Compose file this does **not** ensure that the DB is ready, only that the DB container is alive. I experienced several times that the DB would start after the Backend and the Backend would never try to reconnect, this will atleast stop that from happening. 

## Types of Changes

- [ ] New feature
- [x] Bug fix
- [ ] Enhancement/optimization
- [ ] Refactor
- [ ] Style
- [ ] Build/dependencies
- [ ] Other

## Checklist

- [x] I have added tests to cover my changes (for features/bugs)
- [x] I am pleased with the readability of the code (if not, state where you need input)
- [x] I have tested the changes and verified that they work and do not break anything (to the best of my ability)

2021-11-01 19:43 UTC, Jorgro commented
It is also possible to install the `wait-for-it` in the docker container as it is an debian package: https://tracker.debian.org/pkg/wait-for-it. Do we prefer that or adding the script manually like I did here?

2021-11-01 19:51 UTC, Jorgro commented
An alternative solution would be something like this: https://stackoverflow.com/questions/31746182/docker-compose-wait-for-container-x-before-starting-y

2021-11-02 11:59 UTC, larwaa commented
```dockerfile
depends_on:
    condition:
```
Is no longer document as of [Docker Compose v3](https://docs.docker.com/compose/compose-file/compose-file-v3/#depends_on). As this is only used for local development, one could alternatively add a short sleep script to our existing `entrypoint.sh` to deal with this issue. However, why bother when we can utilize `wait-for-it.sh`?

2021-11-04 16:11 UTC, larwaa requested changes

2021-11-04 16:11 UTC, larwaa commented on backend/wait-for-it.sh
> +fi
newline

2021-11-04 16:12 UTC, Jorgro reviewed
good work! keep it up

2021-11-04 16:12 UTC, Jorgro commented on backend/wait-for-it.sh
> +    exit $WAITFORIT_RESULT
```suggestion
    exit $WAITFORIT_RESULT
    
```

2021-11-04 16:20 UTC, merged